---

apiVersion: v1
kind: Service
metadata:
  name: demo-service-jason
  namespace: jason
  labels:
    app: demo-service-jason
spec:
  type: NodePort
  ports:
  - port: 8701
    targetPort: 8701
    protocol: TCP
    name: http
  selector:
    app: demo-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment-jason
  namespace: jason
spec:
  selector:
    matchLabels:
      app: demo-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-pod
    spec:
      containers:
      - name:  demo-container
        image: k8sdemo:1.0
        ports:
        - containerPort: 8701
